### ISSUE TITLE
integrate backend and frontend deployments

### ISSUE THREAD

**Issue by m9p909** [T18F-SEG491x-QkShare/QuickShareWiki#10]
- need to compile frontend and move the dist to backend
- setup backend root path to deliver static react stuff

**Comment by SanchitPokharel** [comment]
Script to compile the front end 
Have the backend serve the front end
Copy build folder from front end to backend static folder
Follow documentation and set the path to the static backend. 
React app should be in the static folder in the backend

**Comment by m9p909** [comment]
1 already half done
