### ISSUE TITLE
Determine What to do about ios app

### ISSUE THREAD

**Issue by SanchitPokharel** [T18F-SEG491x-QkShare/QuickShareWiki#20]

**Comment by SanchitPokharel** [comment]
I was able to secure a Macbook Air for Development. 
Although the Macbook air may be a little Old, I am feeling pretty optimistic that development will be possible on it. 
Not sure how to take the image from it though, additional research may be required. 
Knowing the history of Apple and how they like making all their products proprietary, I am unsure how we will be able to share the image.
Will be able to get hands on macbook after reading week.

**Comment by carinatam** [comment]
Research has been done and after reading week, when the Macbook is acquired, we can remote control it on our personal laptops with the [following instructions](https://www.howtogeek.com/214220/how-to-access-your-macs-screen-from-windows-and-vice-versa/). The Macbook shall be consistently on at all times.
